name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
    name: Tests (PHP ${{ matrix.php }})
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          extensions: encoding-pmmp/ext-encoding@master

      - name: Load Composer package cache
        uses: actions/cache@v6
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=-1

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/phpunit
